#!/bin/bash

# Quick Start Guide for the Creator Sponsorship Platform
# Run this script to get setup information

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     Creator Sponsorship Platform - Quick Start Guide          ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 PROJECT STRUCTURE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "copilot-sponsorship/"
echo "├── frontend/              Next.js React application (port 3000)"
echo "├── sponsorship-backend/   Go REST API (port 8080)"
echo "└── README.md              Main project documentation"
echo ""

echo "🚀 QUICK START (5 minutes)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "Step 1: Verify Setup"
echo "  $ ./verify-setup.sh"
echo ""

echo "Step 2: Start Backend (Terminal 1)"
echo "  $ cd sponsorship-backend"
echo "  $ go run main.go"
echo "  ✓ Server will start on http://localhost:8080"
echo ""

echo "Step 3: Start Frontend (Terminal 2)"
echo "  $ cd frontend"
echo "  $ npm run dev"
echo "  ✓ Open http://localhost:3000 in your browser"
echo ""

echo "📌 PREREQUISITES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✓ Go 1.21+"
echo "✓ Node.js 18+"
echo "✓ PostgreSQL 14+"
echo "✓ npm or pnpm"
echo ""

echo "🔧 CONFIGURATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Frontend:     frontend/.env.local (already configured)"
echo "Backend:      sponsorship-backend/.env (needs database setup)"
echo ""

echo "🗄️  DATABASE SETUP (Required)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "See: sponsorship-backend/README.md#database-setup"
echo ""
echo "Quick steps:"
echo "  1. Create PostgreSQL database:"
echo "     psql -U postgres"
echo "     CREATE DATABASE sponsorship_db;"
echo "     CREATE USER sponsorship_user WITH PASSWORD 'password';"
echo "     GRANT ALL PRIVILEGES ON DATABASE sponsorship_db TO sponsorship_user;"
echo ""
echo "  2. Create tables (see backend README for SQL schema)"
echo ""

echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📖 Main README:              README.md"
echo "📖 Backend README:           sponsorship-backend/README.md"
echo "📖 Frontend README:          frontend/README.md"
echo "📖 Integration Details:      INTEGRATION_SUMMARY.md"
echo ""

echo "🧪 TESTING THE INTEGRATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Backend health check:"
echo "   curl http://localhost:8080/health"
echo ""
echo "2. Register account:"
echo "   curl -X POST http://localhost:8080/api/auth/register \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"test@example.com\",\"password\":\"test123\"}'"
echo ""
echo "3. Login:"
echo "   curl -X POST http://localhost:8080/api/auth/login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"email\":\"test@example.com\",\"password\":\"test123\"}'"
echo ""

echo "🔗 API ENDPOINTS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Authentication:"
echo "  POST   /api/auth/login          Login user"
echo "  POST   /api/auth/register       Register new user"
echo ""
echo "Sponsorships:"
echo "  GET    /api/sponsorships        List all sponsorships"
echo "  POST   /api/sponsorships        Create sponsorship"
echo "  GET    /api/sponsorships/:id    Get sponsorship details"
echo "  PUT    /api/sponsorships/:id    Update sponsorship"
echo "  DELETE /api/sponsorships/:id    Delete sponsorship"
echo ""
echo "Analytics:"
echo "  GET    /api/dashboard/stats     Dashboard statistics"
echo ""

echo "🐛 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Port already in use:"
echo "  Backend (8080):  lsof -i :8080 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo "  Frontend (3000): lsof -i :3000 | grep LISTEN | awk '{print \$2}' | xargs kill -9"
echo ""
echo "Database connection failed:"
echo "  - Check PostgreSQL is running"
echo "  - Verify .env credentials match database"
echo "  - Ensure database and user exist"
echo ""
echo "Frontend can't reach backend:"
echo "  - Verify NEXT_PUBLIC_API_URL in frontend/.env.local"
echo "  - Check backend is running on port 8080"
echo "  - Verify CORS_ALLOWED_ORIGINS in backend/.env"
echo ""

echo "✅ You're all set!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run verify-setup.sh to check your environment before starting."
echo ""
